spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: pass
        driverClassName: org.h2.Driver
    messages:
        basename: i18n/messages
        encoding: UTF-8
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 431842000604-c6oc1eo91e135bnep9jr1ls06l2rhkpl.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                            - email
                            - profile
                    naver:
                        client-id: xxx
                        client-secret: xxx
                        scope:
                            - name
                            - email
                        #- profile_image
                        client-name: Naver
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8880/login/oauth2/code/naver #코드를 받는 uri(naver 의 콜백 uri)

                    kakao:
                        client-id: xxx
                        client-secret: xxx
                        scope:
                            # - profile_nickname
                            - account_email
                        client-name: Kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: POST #카카오는 필수 파라미터를 POST로 요청해야됌!
                        redirect-uri: http://localhost:8880/login/oauth2/code/kakao #코드를 받는 uri(naver 의 콜백 uri)
                provider: #네이버의 provider는 등록되어 있지 않아 사용자가 등록해야된다.
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize #네이버 로그인 창을 받을수 있다
                        token-uri: https://nid.naver.com/oauth2.0/token #토큰을 받는 uri
                        user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 주소를 받는 uri
                        user-name-attribute: response #회원 벙보를 json 형태로 받는데 response 라는 키값으로 네이버가 리턴해줌

                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: kakao_account
logging:
    level:
        "[org.springframework.web]": debug
        "[com.example.hexagonal]": debug
management:
    endpoints:
        web:
            exposure:
                include: "*"
