spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: pass
        driverClassName: org.h2.Driver
    messages:
        basename: i18n/messages
        encoding: UTF-8
logging:
    level:
        "[org.springframework.web]": debug
        "[com.example.hexagonal]": debug
management:
    endpoints:
        web:
            exposure:
                include: "*"
